### ISSUE TITLE
Problema ao iniciar geraldin no terminal ubuntu

### ISSUE THREAD

**Issue by ricardograff** [renandecarlo/geraldin-bot#4]
Fala Renan, beleza, não encontrei outra forma de falar contigo senão abrindo uma issue no teu projeto.

Sou um usuário do geraldin bot. User: ricardograff@aiqfome.com

Eu costumava deixar o geraldin logado no cloud para não ter problemas como queda de luz e de internet, assim o bot tava sempre lá, vivinho da silva e rodando, agora depois da atualização da autenticação isso não foi mais possível, quando tento subir ele no terminal ele dá um erro: 
"✖ Não foi possível verificar a assinatura no momento. Tente mais tarde." 

Sabe me informar se tem algum workaround para isso? 

Versão do SO e Ubuntu 18.04 LTS

Abraço!

**Comment by renandecarlo** [comment]
Fala Ricardo, blz? Agora como precisa de assinatura, roda somente pelo executável no Windows.
Entra no grupo de suporte do Geraldin pra eu te ajudar melhor: https://chat.whatsapp.com/C9ksB4wF0NqGdLA3L7dXip
